# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Art Lab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Art Lab
  pod 'SVProgressHUD'
  pod 'AFNetworking', '~> 4.0'
  pod 'SocketRocket'
  pod 'SAMKeychain'

end
